"""initial_schema

Revision ID: f254285a977d
Revises: 
Create Date: 2026-03-24 14:21:35.671283
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f254285a977d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('platforms_requested', sa.JSON(), nullable=False),
    sa.Column('platforms_completed', sa.JSON(), nullable=False),
    sa.Column('platforms_failed', sa.JSON(), nullable=False),
    sa.Column('total_items_found', sa.Integer(), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('platform', sa.Enum('YOUTUBE', 'TIKTOK', 'TWITTER', 'INSTAGRAM', 'GOOGLE_TRENDS', name='platform'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('video_url', sa.String(length=2000), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_url', sa.String(length=2000), nullable=True),
    sa.Column('author_followers', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentiment'), nullable=True),
    sa.Column('lifecycle', sa.Enum('RISING', 'PEAK', 'DECLINING', name='trendlifecycle'), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('related_topics', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('cross_platform_ids', sa.JSON(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_items_dedup_key'), 'trend_items', ['dedup_key'], unique=False)
    op.create_index('ix_trend_items_discovered', 'trend_items', ['discovered_at'], unique=False)
    op.create_index('ix_trend_items_platform_category', 'trend_items', ['platform', 'category'], unique=False)
    op.create_index(op.f('ix_trend_items_scan_run_id'), 'trend_items', ['scan_run_id'], unique=False)
    op.create_index('ix_trend_items_score', 'trend_items', ['relevance_score'], unique=False)
    op.create_table('trend_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trend_item_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentiment'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trend_item_id'], ['trend_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_comments_trend_item_id'), 'trend_comments', ['trend_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_comments_trend_item_id'), table_name='trend_comments')
    op.drop_table('trend_comments')
    op.drop_index('ix_trend_items_score', table_name='trend_items')
    op.drop_index(op.f('ix_trend_items_scan_run_id'), table_name='trend_items')
    op.drop_index('ix_trend_items_platform_category', table_name='trend_items')
    op.drop_index('ix_trend_items_discovered', table_name='trend_items')
    op.drop_index(op.f('ix_trend_items_dedup_key'), table_name='trend_items')
    op.drop_table('trend_items')
    op.drop_table('scan_schedules')
    op.drop_table('scan_runs')
    # ### end Alembic commands ###
